### ISSUE TITLE
Missing implementation of parse_bbox_file

### ISSUE THREAD

**Issue by Jonas-Zhang97** [coldmanck/VidHOI#19]
Hello, @coldmanck 

Thank you for your great work.

I'm currently trying to train and run the st-hoi based on vidor, but it seems that one of the required module, i.e. parse_bbox_file, for demo (with input video or webcam) is not implemented in ava_helper, is there any way to get the module?

The error message looks like follows:

```bash
Traceback (most recent call last):
  File "tools/run_net_vidor.py", line 8, in <module>
    from demo_net_vidor import demo
  File "/home/zhihao/hoi_evaluation_project/hoi_models/hoi_st/tools/demo_net_vidor.py", line 11, in <module>
    from slowfast.visualization.ava_demo_precomputed_boxes import (
  File "/home/zhihao/hoi_evaluation_project/hoi_models/hoi_st/slowfast/visualization/ava_demo_precomputed_boxes.py", line 13, in <module>
    from slowfast.datasets.ava_helper import parse_bboxes_file
ImportError: cannot import name 'parse_bboxes_file'
```

Or alternatively is there any way to get the demo running?

Thank you in advance!

**Comment by Jonas-Zhang97** [comment]
I see that the purpose of this module is to load "pre-computed predicted boxes" and thus maybe not needed for demo, so I will close this issue, but any comment is welcome
